name: gitfitbot CI
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-latest-image:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITFITBOT_GITHUB_TOKEN }}
          image-name: gitfitbot
          image-tag: latest
