name: gitfitbot CI
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-latest-image:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@3c0a6ca5c66e31614579048b57259114fb69ac28
        with:
          github-token: ${{ secrets.GITFITBOT_GITHUB_TOKEN }}
          image-name: gitfitbot
          image-tag: latest
