name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: ⎔ Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
        with:
          version: 10
          run_install: true

      - name: 🔬 Lint
        run: pnpm lint:strict

      - name: 🔎 Type check
        run: pnpm typecheck

      - name: 💅 Prettier check
        run: pnpm format:check

  release:
    # run release if event is push and the head commit's commit message does NOT starts with `bump:`
    if: ${{ github.event_name == 'push' && ! startsWith(github.event.head_commit.message , 'bump:') }}
    name: ⬆️ Bump version and create changelog with a GitHub release
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          token: ${{ secrets.SVC_PAT }}

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@a49cac8e98f3954a16e107f026f71cf84b17706c
        with:
          github_token: ${{ secrets.SVC_PAT }}
          changelog_increment_filename: body.md

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          body_path: 'body.md'
          tag_name: ${{ env.REVISION }} # this is the version set in the previous step
          token: ${{ secrets.SVC_PAT }}
          generate_release_notes: true
