name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    # create a release if the head commit's commit message does NOT starts with `bump:`
    if: ${{ ! startsWith(github.event.head_commit.message , 'bump:') }}
    name: ⬆️ Bump version and create changelog with a GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          token: ${{ secrets.SVC_PAT }}

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@a49cac8e98f3954a16e107f026f71cf84b17706c
        with:
          github_token: ${{ secrets.SVC_PAT }}
          changelog_increment_filename: body.md

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          body_path: 'body.md'
          tag_name: ${{ env.REVISION }} # this is the version set in the previous step
          token: ${{ secrets.SVC_PAT }}
          generate_release_notes: true
